from models import db, State, User
from app import app

db.drop_all()
db.create_all()

AL = State(id='AL', name='Alabama')
AK = State(id='AK', name='Alaska')
AR = State(id='AR', name='Arkansas')
AZ = State(id='AZ', name='Arizona')
CA = State(id='CA', name='California')
CO = State(id='CO', name='Colorado')
CT = State(id='CT', name='Connecticut')
DE = State(id='DE', name='Delaware')
DC = State(id='DC', name='District of Columbia')
FL = State(id='FL', name='Florida')
GA = State(id='GA', name='Georgia')
HI = State(id='HI', name='Hawaii')
ID = State(id='ID', name='Idaho')
IL = State(id='IL', name='Illinois')
IN = State(id='IN', name='Indiana')
IA = State(id='IA', name='Iowa')
KS = State(id='KS', name='Kansas')
KY = State(id='KY', name='Kentucky')
LA = State(id='LA', name='Louisiana')
ME = State(id='ME', name='Maine')
MD = State(id='MD', name='Maryland')
MA = State(id='MA', name='Massachusetts')
MI = State(id='MI', name='Michigan')
MN = State(id='MN', name='Minnesota')
MS = State(id='MS', name='Mississippi')
MO = State(id='MO', name='Missouri')
MT = State(id='MT', name='Montana')
NE = State(id='NE', name='Nebraska')
NV = State(id='NV', name='Nevada')
NH = State(id='NH', name='New Hampshire')
NJ = State(id='NJ', name='New Jersey')
NM = State(id='NM', name='New Mexico')
NY = State(id='NY', name='New York')
NC = State(id='NC', name='North Carolina')
ND = State(id='ND', name='North Dakota')
OH = State(id='OH', name='Ohio')
OK = State(id='OK', name='Oklahoma')
OR = State(id='OR', name='Oregon')
PA = State(id='PA', name='Pennsylvania')
RI = State(id='RI', name='Rhode Island')
SC = State(id='SC', name='South Carolina')
SD = State(id='SD', name='South Dakota')
TN = State(id='TN', name='Tennessee')
TX = State(id='TX', name='Texas')
UT = State(id='UT', name='Utah')
VT = State(id='VT', name='Vermont')
VA = State(id='VA', name='Virginia')
WA = State(id='WA', name='Washington')
WV = State(id='WV', name='West Virginia')
WI = State(id='WI', name='Wisconsin')
WY = State(id='WY', name='Wyoming')

db.session.add_all([ AK, AL, AR, AZ, CA, CO, CT, DE, DC, FL, GA, HI, ID, IL, IN, IA, KS, KY, LA, ME, MD, MA, MI, MN, MS, MO, MT, NE, NV, NH, NJ, NM, NY, NC, ND, OH, OK, OR, PA, RI, SC, SD, TN, TX, UT, VT, VA, WA, WV, WI, WY])
db.session.commit()