STATE_REGISTRATION_URLS = {
 'AL': 'https://www.sos.alabama.gov/alabama-votes/voter/register-to-vote?ref=voteusa',
 'AK': 'https://www.elections.alaska.gov/Core/voterregistration.php',
 'AS': 'https://aselectionoffice.gov/?ref=voteusa',
 'AZ': 'https://azsos.gov/elections/voting-election/register-vote-or-update-your-current-voter-information',
 'AR': 'https://www.sos.arkansas.gov/elections/for-voters',
 'CA': 'https://registertovote.ca.gov/',
 'CO': 'https://www.sos.state.co.us/voter/pages/pub/olvr/verifyNewVoter.xhtml',
 'CT': 'https://voterregistration.ct.gov/OLVR/welcome.do',
 'DE': 'https://ivote.de.gov/VoterView', 
 'DC': 'https://www.dcboe.org/Voters/Register-To-Vote/Register-to-Vote',
 'FM': 'https://www.fsmned.fm/voters_instructions.html',
 'FL': 'https://registertovoteflorida.gov/home', 
 'GA': 'https://georgia.gov/register-to-vote',
 'GU': 'https://gec.guam.gov/',
 'HI': 'https://elections.hawaii.gov/register-to-vote/registration/',
 'ID': 'https://elections.sos.idaho.gov/ElectionLink/ElectionLink/ApplicationInstructions.aspx',
 'IL': 'https://ova.elections.il.gov/?Name=Em5DYCKC4wXCKQSXTgsQ9knm%2b5Ip27VC&T=637623864062530637',
 'IN': 'https://www.in.gov/sos/elections/voter-information/register-to-vote/',
 'IA': 'https://sos.iowa.gov/elections/voterinformation/voterregistration.html',
 'KS': 'https://www.kdor.ks.gov/Apps/VoterReg/Default.aspx',
 'KT': 'https://fj.usembassy.gov/u-s-citizen-services/voting/',
 'LA': 'https://www.sos.la.gov/ElectionsAndVoting/RegisterToVote/Pages/default.aspx',
 'ME': 'https://www.maine.gov/sos/cec/elec/voter-info/votreg.html',
 'MH': 'https://mh.usembassy.gov/u-s-citizen-services/voting/voting-faqs/',
 'MD': 'https://elections.maryland.gov/voter_registration/index.html',
 'MA': 'https://www.sec.state.ma.us/OVR/',
 'MI': 'https://mvic.sos.state.mi.us/Home/RegisterToVote',
 'MN': 'https://www.sos.state.mn.us/elections-voting/register-to-vote/',
 'MS': 'https://www.sos.ms.gov/elections-voting/voter-registration-information',
 'MO': 'https://www.sos.mo.gov/elections/goVoteMissouri/register',
 'MT': 'https://sosmt.gov/elections/vote/',
 'NE': 'https://www.nebraska.gov/apps-sos-voter-registration/',
 'NV': 'https://www.nvsos.gov/sos/elections/voters/registering-to-vote',
 'NH': 'https://sos.nh.gov/elections/voters/register-to-vote/',
 'NJ': 'https://nj.gov/state/elections/voter-registration.shtmll',
 'NM': 'https://portal.sos.state.nm.us/OVR/WebPages/InstructionsStep1.aspx',
 'NY': 'https://www.elections.ny.gov/VotingRegister.html',
 'NC': 'https://www.ncsbe.gov/registering',
 'ND': 'https://vote.nd.gov/PortalListDetails.aspx?ptlhPKID=73&ptlPKID=5',
 'MP': 'https://www.votecnmi.gov.mp/',
 'OH': 'https://olvr.ohiosos.gov/',
 'OK': 'https://oklahoma.gov/elections/voter-info/register-to-vote.html',
 'OR': 'https://sos.oregon.gov/voting/Pages/registration.aspx?lang=en',
 'PW': 'https://pw.usembassy.gov/u-s-citizen-services/voting/',
 'PA': 'https://www.pavoterservices.pa.gov/Pages/VoterRegistrationApplication.aspx',
 'PR': 'https://ww2.ceepur.org/Home/Index?aspxerrorpath=/es-pr/Paginas/cee-english.aspx',
 'RI': 'https://vote.sos.ri.gov/Home/RegistertoVote?ActiveFlag=1',
 'SC': 'https://www.scvotes.gov/south-carolina-voter-registration-information',
 'SD': 'https://sdsos.gov/elections-voting/voting/register-to-vote/default.aspx',
 'TN': 'https://sos.tn.gov/products/elections/register-vote',
 'TX': 'https://www.votetexas.gov/register/index.html',
 'UT': 'https://voteinfo.utah.gov/learn-about-registering-to-vote/',
 'VT': 'https://sos.vermont.gov/elections/voters/registration/',
 'VI': 'https://www.vivote.gov/',
 'VA': 'https://www.elections.virginia.gov/registration/',
 'WA': 'https://voter.votewa.gov/WhereToVote.aspx',
 'WV': 'https://ovr.sos.wv.gov/Register/Landing',
 'WI': 'https://myvote.wi.gov/en-us/Register-To-Vote',
 'WY': 'https://sos.wyo.gov/Elections/State/RegisteringToVote.aspx'}

US_STATES = {
  "AL": "Alabama",
  "AK": "Alaska",
  "AS": "American Samoa",
  "AZ": "Arizona",
  "AR": "Arkansas",
  "CA": "California",
  "CO": "Colorado",
  "CT": "Connecticut",
  "DE": "Delaware",
  "DC": "District Of Columbia",
  "FM": "Federated States Of Micronesia",
  "FL": "Florida",
  "GA": "Georgia",
  "GU": "Guam",
  "HI": "Hawaii",
  "ID": "Idaho",
  "IL": "Illinois",
  "IN": "Indiana",
  "IA": "Iowa",
  "KS": "Kansas",
  "KY": "Kentucky",
  "LA": "Louisiana",
  "ME": "Maine",
  "MH": "Marshall Islands",
  "MD": "Maryland",
  "MA": "Massachusetts",
  "MI": "Michigan",
  "MN": "Minnesota",
  "MS": "Mississippi",
  "MO": "Missouri",
  "MT": "Montana",
  "NE": "Nebraska",
  "NV": "Nevada",
  "NH": "New Hampshire",
  "NJ": "New Jersey",
  "NM": "New Mexico",
  "NY": "New York",
  "NC": "North Carolina",
  "ND": "North Dakota",
  "MP": "Northern Mariana Islands",
  "OH": "Ohio",
  "OK": "Oklahoma",
  "OR": "Oregon",
  "PW": "Palau",
  "PA": "Pennsylvania",
  "PR": "Puerto Rico",
  "RI": "Rhode Island",
  "SC": "South Carolina",
  "SD": "South Dakota",
  "TN": "Tennessee",
  "TX": "Texas",
  "UT": "Utah",
  "VT": "Vermont",
  "VI": "Virgin Islands",
  "VA": "Virginia",
  "WA": "Washington",
  "WV": "West Virginia",
  "WI": "Wisconsin",
  "WY": "Wyoming"
}